### ISSUE TITLE
The referenced component 'ARMProxy.Workers.Hubs" could not be found

### ISSUE THREAD

**Issue by Abdelkrim** [MicrosoftDX/AzureLens#2]
Several errors occur when I try to build AzureLens using Visual Studio 2015 Update 2: 

**Where can I foudn the 'ARMProxy.Workers.Hub' package?**
- The referenced component 'ARMProxy.Workers.Hubs' could not be found.
- The referenced project '..\ARMProxy.Workers.Hubs\ARMProxy.Workers.Hubs.csproj' does not exist
- CS0246 The type or namespace name 'ARMProxy' could not be found (are you missing a using directive or an assembly reference?) AzureLens   C:\AzureLens\AzureLens\Hubs\MonitorQueue.cs 9

![armproxy workers hubs](https://cloud.githubusercontent.com/assets/791663/14502595/4272eee4-01ac-11e6-81da-cf060328f43d.PNG)

**Comment by matvelloso** [comment]
Sorry for the mess. Please ignore the ARMProxy completely. That was a very early prototype and we didn't manage to finish it yet. I'll fix that when I get some time, but basically there has been no ARM integration built yet (it was our dream but we just didn't have time to get here yet).

**Comment by Abdelkrim** [comment]
Dear @matvelloso  do you mean that I have to delete the Hubs directory and all related methods /  classes / functions? 

thanks for your swift feedback

**Comment by matvelloso** [comment]
That's it. Delete anything that references the hubs, including the javascript code calling it with a timer (the only reason it's there right now is to simulate changing the status of a VM so it changes colors, so it does nothing real)

**Comment by Abdelkrim** [comment]
@matvelloso is it not easier if you add the code even if it does nothing ? ;-)

then, we can close the comment

**Comment by matvelloso** [comment]
I promise it's in my to do list, just can't give you an ETA yet, sorry

**Comment by Abdelkrim** [comment]
thank you, I'm the one who will be grateful to read your future piece of code

**Comment by matvelloso** [comment]
Sorry for the delay. Just updated with a new version that should build more easily now

**Comment by Abdelkrim** [comment]
great, I'll test it soon
